"""Frozen evidence declarations for the research-direction audit.

This module contains no controller or mapping implementation.  Its records are
used by ``build_direction_audit.py`` to create reviewable CSV/JSON/Markdown
artifacts from frozen upstream evidence and primary-source literature.
"""

from __future__ import annotations

WORKSTREAMS = [
    ("R1", "Splat-Nav / SAFER-Splat reproduction", "Can published Gaussian-map navigation and filtering be reproduced?", "A reproducible baseline and honest system boundary", "Reproduction harnesses, protocol locks, runtime repairs, G0/G1 checks", "Stonehenge, Flight, TUM", "Published pipelines were recovered and bounded static/runtime checks became repeatable", "End-to-end success was not uniform across maps; several failures were protocol or geometry failures", "Compatibility or a smoke test is not formal navigation success", "Reproduction assets and failure taxonomy remain usable", "reproduction/, protocol validators", "Frozen maps, registries, logs", "Identity, runtime, and bounded-query validators", "Reproduction and failure-analysis evidence", "No universal safe-navigation or cross-dataset success claim", "High", "High"),
    ("R2", "Risk-Aware candidate filtering V0/V1/BestD", "Can active-set filtering reduce SAFER query cost?", "Efficiency without weakening frozen constraints", "Risk-aware candidate filters, ablations, BestD selection", "Stonehenge and Flight frozen trials", "Constraint/query reduction and efficiency signals were observed", "No new safety benefit was established", "Efficiency improvement is not a safety improvement", "Useful pruning and profiling machinery", "Risk-aware filters and profilers", "Frozen trial manifests", "Runtime and constraint-count comparison", "Efficiency/constraint-reduction evidence", "No collision-superiority or new-safety claim", "Medium", "High"),
    ("R3", "Cross-dataset map qualification Protocol V2", "When is a Gaussian map admissible for navigation claims?", "A metric-provenance and reference-authority gate", "Map provenance, scale, coordinate, reference, and split audits", "Replica, ETH3D, TUM, ARKitScenes", "Fail-closed qualification exposed which assets can support which claims", "Most learned maps lacked two-map reference-complete evaluation", "Photorealism or import success does not establish navigation geometry", "Protocol V2 and reference hierarchy remain central", "Qualification validators", "Map/reference identity manifests", "Map readiness matrices", "Measurement and negative-evidence claims", "No deployment qualification for failed maps", "High", "Very high"),
    ("R4", "TUM Splatfacto and geometry drift", "Can a learned Splatfacto map preserve metric navigation geometry?", "A trained TUM baseline with usable safety geometry", "Formal training lineage, checkpoint audit, geometry refinement ablations", "TUM fr1/room", "Training and rendering were recovered; causes of several runtime failures were identified", "Post-3K geometry drift and map/reference mismatch prevented formal navigation use", "Good rendering metrics do not imply trustworthy collision geometry", "Negative control and geometry diagnostics", "Training/evaluation audit scripts", "TUM data and frozen checkpoints", "Depth/geometry drift evaluations", "Negative evidence about geometry reliability", "TUM Splatfacto is not a formal navigation map", "High", "Medium"),
    ("R5", "TUM SplaTAM / Gaussian-SLAM baselines", "Do dedicated RGB-D Gaussian SLAM maps improve metric geometry?", "Alternative learned-map baselines", "Adapters, metric-pose audits, static SAFER queries", "TUM RGB-D", "Dedicated RGB-D frontends improved provenance and compatibility understanding", "No two-independent-map claim-ready reference split emerged", "A loadable map is not a qualified cross-map benchmark", "Adapters and map schema audits", "Common map adapter", "TUM trajectories and maps", "Static geometry/query audit", "Bounded compatibility evidence", "No broad mapping or navigation superiority", "Medium", "High"),
    ("R6", "Start-Safe diagnosis and projection", "Why do nominal direct-goal trials stall or start unsafe?", "Protocol-correct start/goal and projection diagnostics", "Direct-safe pair search, projection and geometric root-cause tools", "TUM and Replica", "Separated initial infeasibility from later controller limitation", "Some candidate schedules never reached the intended activation regime", "A failed trajectory can be an invalid scenario rather than a controller verdict", "Scenario admissibility and start-safe tools", "Geometry/projector diagnostics", "Frozen start-goal registries", "Preflight and counterexample evidence", "No method superiority from inadmissible trials", "Medium", "High"),
    ("R7", "Discrete-Time verification", "Do continuous barrier checks survive sampled execution?", "A discrete-time numerical contract", "Float64 boundary certification, Hessian calibration, sampled-step audits", "TUM and synthetic boundary cases", "Numerical contracts and boundary-event certifications were established", "Continuous-time intuition alone was insufficient", "Continuous certificates do not automatically imply sampled-data safety", "Float64 certification harness", "Boundary-event records", "Numerical parity tests", "Numerical contract evidence", "No global closed-loop theorem", "Medium", "High"),
    ("R8", "Predictive Recovery / HCE", "Can predictive trigger/recovery avoid boundary stalls?", "A trigger-conditioned recovery module", "V4-C trigger, HCE recovery, preregistered pair schedules", "TUM SplaTAM", "Specific development/heldout cases reached the trigger and recovery logic", "Representative progress and overlap were too limited; paired20 was paused after two results", "Stress-case activation cannot replace representative prevalence", "Trigger/recovery logging and serial scheduler", "Heldout pair registry", "Paired protocol and float64 certifier", "Bounded mechanism/counterexample evidence", "No full 20-pair or general navigation claim", "High", "Medium"),
    ("R9", "Module-wise evidence assembly", "Which submodules have support independent of the full stack?", "Module-specific claims with explicit nonclaims", "Evidence traceability, claim matrices, component audits", "Frozen prior runs", "Positive and negative evidence became auditable by module", "The evidence did not compose into an automatic end-to-end guarantee", "Module validity does not imply system validity", "Traceability and claim-boundary tooling", "Compact evidence registries", "Claim-evidence audits", "Modular assurance evidence", "No transitive full-stack safety claim", "Low", "Very high"),
    ("R10", "Core V1 conceptual closure", "What is the smallest coherent FAS-CBF core?", "Actuator-bounded swept, terminal, and alternative semantics", "State machine, certificate schema, theory obligations, interfaces", "No new data", "A coherent fail-closed executable contract was frozen", "Several proof obligations remain empirical or open", "Conceptual closure is not empirical qualification", "Core V1 contracts and schemas", "No new map data", "Unit/integration test specifications", "Problem formulation and bounded design evidence", "No certified system claim", "Low", "Very high"),
    ("R11", "Unified executable safety certifier", "Can the Core V1 contract be executed with typed outcomes?", "A unified B0-B3 executable certifier", "Nested method matrix, represented-space alternatives, failure typing", "Replica GT-derived map", "Executable semantics and nested ablations were validated", "Representative activation was not demonstrated at this stage", "Passing unit and method tests is not representative utility", "Unified certifier implementation", "Replica GT-derived asset", "Method fairness and contract tests", "Executable-mechanism evidence", "No broad replacement or learned-map claim", "Medium", "Very high"),
    ("R12", "Replica GT activated and representative benchmark", "Does Core V1 activate and help, and how prevalent is that need?", "Causal B0-B3 evidence plus a representative prevalence audit", "100 activated states, 160 representative holdout states, 1040 one-step records, 640 episodes", "Replica GT-derived Gaussian plus independent mesh", "Activated G0-G5 quotas were met and the mechanism was exercised without represented false-safe events", "Representative segment, backup, and directional activation were 0/160; B3 missed 50 ms on 116/260 one-step records", "0/160 is not method failure, but pressure cases cannot overwrite it", "Complete benchmark/validator/report stack", "Qualified Replica map and reference mesh", "Nested paired benchmark and reference oracle", "Strongest current mechanism and limitation evidence", "No broad real-time SAFER replacement; no collision superiority from zero reference-collision events", "Medium", "Very high"),
]

ASSETS = [
    ("A01", "Protocol V2 metric provenance gate", "protocol", "R3", "ready", "Map/reference claim scoping"),
    ("A02", "Replica GT-derived Gaussian map identity", "map", "R12", "ready", "Single-map controlled evaluation"),
    ("A03", "Replica independent mesh identity", "reference", "R12", "ready", "Offline geometry oracle"),
    ("A04", "Activated registry G0-G5", "registry", "R12", "ready", "Mechanism stress cohort only"),
    ("A05", "Representative holdout registry", "registry", "R12", "ready", "Prevalence estimate on one map"),
    ("A06", "B0-B3 nested method registry", "method_contract", "R11", "ready", "Causal module ablation"),
    ("A07", "Unified typed certificate schema", "schema", "R10", "ready", "Executable semantics"),
    ("A08", "Fail-closed state machine", "schema", "R10", "ready", "Unknown/failure handling"),
    ("A09", "Actuator-box check", "module", "R11", "ready", "Bounded input semantics"),
    ("A10", "Swept-segment certificate", "module", "R11", "ready", "Short represented-space segment query"),
    ("A11", "Terminal backup certificate", "module", "R11", "ready", "Bounded represented-space backup rollout"),
    ("A12", "Directional alternative library", "module", "R11", "ready", "Frozen alternative set"),
    ("A13", "Reference-oracle no-leak contract", "protocol", "R12", "ready", "Offline-only evaluation"),
    ("A14", "Reference mesh oracle", "evaluation", "R12", "ready", "Swept collision and clearance"),
    ("A15", "One-step paired benchmark", "evaluation", "R12", "ready", "Nested method comparison"),
    ("A16", "Bounded logical rollout", "evaluation", "R12", "ready", "Short closed-loop diagnostic"),
    ("A17", "Float64 boundary certifier", "evaluation", "R7", "ready", "Post-hoc numerical checks"),
    ("A18", "Ellipsoid functional-autograd solver parity", "evaluation", "R7", "ready", "Numerical contract"),
    ("A19", "World-frame stable Hessian correction", "module", "R7", "ready", "Stable second-order query"),
    ("A20", "Risk-aware BestD filter", "module", "R2", "ready", "Efficiency-only ablation"),
    ("A21", "Constraint/query profiler", "evaluation", "R2", "ready", "Runtime decomposition"),
    ("A22", "TUM SplaTAM adapter", "adapter", "R5", "ready", "Static compatibility only"),
    ("A23", "Gaussian-SLAM common adapter", "adapter", "R5", "ready", "Static compatibility only"),
    ("A24", "Splatfacto checkpoint audit", "negative_evidence", "R4", "ready", "Geometry-drift analysis"),
    ("A25", "TUM map geometry diagnostic suite", "evaluation", "R4", "ready", "Metric drift and scale"),
    ("A26", "Start-safe pair validator", "evaluation", "R6", "ready", "Scenario admission"),
    ("A27", "Direct-path geometry audit", "evaluation", "R6", "ready", "Protocol diagnosis"),
    ("A28", "V4-C trigger/recovery log schema", "schema", "R8", "ready", "Mechanism traceability"),
    ("A29", "Heldout pair serial scheduler", "protocol", "R8", "paused", "Resume without rerunning terminals"),
    ("A30", "Core V1 proof-obligation registry", "theory", "R10", "ready", "Separates proved/empirical/open"),
    ("A31", "Claim-evidence traceability matrix", "audit", "R9", "ready", "Paper claim audit"),
    ("A32", "Method fairness audit", "audit", "R11", "ready", "Shared-input and nestedness checks"),
    ("A33", "Selection leakage audit", "audit", "R12", "ready", "Activated vs representative separation"),
    ("A34", "Deadline audit", "audit", "R12", "ready", "50 ms runtime boundary"),
    ("A35", "Map-reference disagreement audit", "audit", "R12", "ready", "Represented vs mesh discrepancy"),
    ("A36", "Cross-dataset evidence inventory", "registry", "R3", "ready", "Asset/readiness routing"),
]

HYPOTHESES = [
    ("H01", "Risk-aware filtering adds safety beyond SAFER", "falsified", "Observed benefit is efficiency/constraint reduction, not new safety"),
    ("H02", "TUM Splatfacto rendering quality implies navigation geometry", "falsified", "Post-3K metric geometry drift and reference mismatch"),
    ("H03", "Import-only gsplat probe qualifies CUDA backend", "falsified", "_C was None until functional forward/backward qualification"),
    ("H04", "Map loadability establishes Protocol V2 qualification", "falsified", "Reference authority and metric provenance remain independent gates"),
    ("H05", "Start failure necessarily indicts controller", "falsified", "Several failures were start-safe/protocol/geometry inadmissibility"),
    ("H06", "Continuous CBF evaluation is enough for sampled execution", "falsified", "Boundary and finite-step certification were separately required"),
    ("H07", "Stress-case recovery proves representative benefit", "falsified", "Representative segment/backup/directional prevalence was 0/160"),
    ("H08", "Activated cohort estimates field prevalence", "falsified", "Activated cohort is deliberately selection-biased"),
    ("H09", "Zero represented false-safe establishes collision superiority", "falsified", "Reference collision event count was zero in the relevant representative comparison"),
    ("H10", "Core V1 can be claimed as broad SAFER replacement", "falsified", "Representative activation was absent and B3 deadline miss was 44.62%"),
    ("H11", "Module correctness composes automatically into system safety", "falsified", "Open assumptions and end-to-end evidence gaps remain"),
    ("H12", "The finite directional library guarantees recovery", "falsified", "It is a bounded candidate set, not a viability proof"),
    ("H13", "A single qualified map is enough for learned-map generalization", "falsified", "No two-map credible-reference split exists"),
    ("H14", "Photometric metrics are sufficient geometry authority", "falsified", "Robotics collision claims require mesh/depth/ray authority"),
    ("H15", "Unknown map regions can be treated as free by default", "falsified", "Protocol V2 requires fail-closed or explicit UNKNOWN semantics"),
    ("H16", "A wrapper/runtime repair changes scientific attempt identity", "falsified", "Nonsemantic repairs were isolated while frozen tokens stayed fixed"),
    ("H17", "The 20-pair paused schedule is a completed benchmark", "falsified", "Only two terminal scientific rollouts were preserved"),
    ("H18", "More direction churn is justified by sunk engineering cost", "falsified", "Selection must be based on novelty, data readiness, and bounded deliverability"),
]

PAPERS = [
    # id, title, year, status, categories, included, fulltext, code, url, key evidence, overlap, limitation pointer
    ("2209.12266", "NeRF-CBF: Safety- and Stability-Critical Control with Neural Radiance Fields", 2022, "arXiv", "C9;C10", True, False, False, "https://arxiv.org/abs/2209.12266", "Neural-field perception is embedded in a CBF-based feedback loop", "Precursor for implicit-map safety control", "Not a Gaussian-map uncertainty qualification study"),
    ("2304.00194", "Safe Perception-Based Control under Stochastic Sensor Uncertainty using Conformal Prediction", 2023, "primary manuscript", "C7;C10", True, True, False, "https://arxiv.org/abs/2304.00194", "Conformal state-estimation sets combine with measurement-robust sampled-data CBFs", "High for D3/D8 calibration semantics", "Assumes exchangeability/calibration coverage; not 3DGS-specific"),
    ("2309.08050", "Robust Control Barrier Functions for Sampled-Data Systems", 2023, "primary manuscript", "C8", True, True, False, "https://arxiv.org/abs/2309.08050", "Robust CBF constraints explicitly account for sampling, disturbance, and measurement error", "Theory baseline for D1/D4", "Not a Gaussian-map method"),
    ("2403.02751", "Splat-Nav: Safe Real-Time Robot Navigation in Gaussian Splatting Maps", 2024, "RA-L 2024", "C1;C3", True, True, True, "https://arxiv.org/abs/2403.02751", "Safe polytope planning plus vision localization; 126 hardware flights and 2 Hz replanning", "Strong navigation baseline for D2/D5/D7", "Planning corridor rather than selective map truth or backup-CBF semantics"),
    ("2405.00362", "Implicit Swept Volume SDF: Enabling Continuous Collision-Free Trajectory Generation for Arbitrary Shapes", 2024, "ACM TOG 2024", "C9", True, True, True, "https://arxiv.org/abs/2405.00362", "Continuous swept-volume SDF for arbitrary-shape trajectory optimization", "Strong geometric baseline for D2", "Not Gaussian-map-specific and no map-reference uncertainty"),
    ("2405.10142", "GS-Planner: A Gaussian-Splatting-based Planning Framework for Active High-Fidelity Reconstruction", 2024, "IROS 2024", "C1;C4", True, True, False, "https://arxiv.org/abs/2405.10142", "Gaussian active reconstruction with a safety-aware trajectory planning constraint", "Baseline for planning/active mapping", "Reconstruction objective and safety constraint differ from executable filter qualification"),
    ("2409.09868", "A Control Barrier Function for Safe Navigation with Online Gaussian Splatting Maps", 2024, "RA-L 2025", "C2;C5", True, True, True, "https://arxiv.org/abs/2409.09868", "SAFER-Splat performs online Gaussian mapping and minimally invasive CBF filtering", "Direct baseline and origin of current work", "Uses reduced-order dynamics and does not establish our cross-map reference contract"),
    ("2409.16915", "Let's Make a Splan: Risk-Aware Trajectory Optimization in a Normalized Gaussian Splat", 2024, "ICRA 2025", "C1;C3;C10", True, True, False, "https://arxiv.org/abs/2409.16915", "Bounds collision probability in a normalized splat and optimizes risk-aware trajectories", "Strong D2/D5/D6 overlap", "Trajectory optimization rather than selective false-free query"),
    ("2407.03569", "Adaptive Conformal Safety Control", 2024, "arXiv", "C7;C10", True, False, False, "https://arxiv.org/abs/2407.03569", "Online adaptive conformal calibration for safety control", "Calibration baseline for D3/D8", "Not 3DGS-specific"),
    ("2505.08510", "FOCI: Trajectory Optimization on Gaussian Splats", 2025, "IROS 2025", "C1;C3", True, True, True, "https://arxiv.org/abs/2505.08510", "Gaussian overlap collision integral supports orientation-aware differentiable optimization", "High D2/D5 overlap", "Optimization geometry is not a one-sided cross-map truth certificate"),
    ("2509.14421", "Perception-Integrated Safety Critical Control via Analytic Collision Cone Barrier Functions on 3D Gaussian Splatting", 2025, "arXiv", "C2;C5", True, True, False, "https://arxiv.org/abs/2509.14421", "Analytic forward collision cones from individual splats yield first-order CBF-QP constraints", "Very high D2/D5 overlap", "No calibrated false-free UNKNOWN contract or two-map reference study found"),
    ("2604.18205", "A Comparative Evaluation of Geometric Accuracy in NeRF and Gaussian Splatting", 2026, "arXiv", "C6", True, True, False, "https://arxiv.org/abs/2604.18205", "Evaluates rendering representations with independent geometry metrics across 19 scenes", "Measurement baseline for D7", "Not a navigation/control benchmark"),
    ("2605.20566", "Conflict-Aware Active Perception and Control in 3D Gaussian Splatting Fields via Control Barrier Functions", 2026, "arXiv", "C2;C4;C10", True, True, False, "https://arxiv.org/abs/2605.20566", "AV@R collision risk and an information-gain CBF are combined in one QP", "High D3/D8 overlap", "Simulation-focused and active-perception objective differs from reference-qualified abstention"),
    ("2605.30342", "Uncertainty-driven 3D Gaussian Splatting Active Mapping via Anisotropic Visibility Field", 2026, "CVPR 2026", "C4;C5", True, True, False, "https://openaccess.thecvf.com/content/CVPR2026/html/Xue_Uncertainty-driven_3D_Gaussian_Splatting_Active_Mapping_via_Anisotropic_Visibility_Field_CVPR_2026_paper.html", "GAVIS learns anisotropic visibility uncertainty and supports fast active mapping", "High D3/D8 map-confidence overlap", "Uncertainty targets active mapping, not one-sided false-free control certification"),
    ("2606.00297", "Predicted-Flow Control Barrier Functions for Real-Time Safe Optimal Control", 2026, "IEEE Access 2026", "C8;C10", True, True, True, "https://arxiv.org/abs/2606.00297", "Prediction-horizon barrier and terminal backup set yield a jointly feasible real-time QP", "High D4/D5 overlap", "Not Gaussian-map-specific"),
    ("2607.01200", "FastBridge: Closing the Model-Based Realization Gap in Safety Filters on 3D Gaussian Splatting for Fast Quadrotor Flight", 2026, "arXiv", "C2;C5;C8", True, True, False, "https://arxiv.org/abs/2607.01200", "Full quadrotor dynamics, actuator-aware constraints, analytic collision-cone ECBF, and forward-simulated backup CBF", "Most direct D1/D4 competitor and high D5 overlap", "Initial hardware validation; does not supply our map-reference qualification benchmark"),
    ("2607.08948", "SplatCtrl: Perception-Action Coupling via Gaussian Scene Representations and Reactive Robot Control", 2026, "arXiv", "C2;C5", True, True, False, "https://arxiv.org/abs/2607.08948", "Online RGB-D isotropic splats feed continuous collision fields and CBF reactive manipulator control", "High D5/D8 overlap", "Sphere approximation, tuning, and scalability are stated limitations"),
    ("2603.10392", "Safe Probabilistic Planning using Conformal Risk Control", 2026, "arXiv", "C7;C10", True, False, False, "https://arxiv.org/abs/2603.10392", "Conformal risk control calibrates probabilistic planning decisions", "D3/D8 statistical baseline", "Not 3DGS-specific"),
    ("2603.15186", "NavGSim: Navigation in Gaussian Splatting Simulations", 2026, "arXiv", "C1;C6", False, False, False, "https://arxiv.org/abs/2603.15186", "Recent Gaussian-simulation navigation benchmark candidate", "Possible D7 neighbor", "Excluded from method matrix pending full benchmark/reference audit"),
    ("2602.12159", "3DGSNav: Navigating with 3D Gaussian Splatting", 2026, "arXiv", "C1", False, False, False, "https://arxiv.org/abs/2602.12159", "Recent Gaussian-navigation pipeline candidate", "Landscape context", "Excluded from high-relevance matrix after abstract screening"),
    ("2607.05522", "Bayesian 3D Gaussian Splatting", 2026, "arXiv", "C4", False, False, False, "https://arxiv.org/abs/2607.05522", "Bayesian uncertainty for 3DGS", "D3/D8 context", "Excluded because control/query evidence was not primary focus"),
    ("2605.30696", "BP-SDF: Barrier-Preserving Signed Distance Fields for Safe Control", 2026, "arXiv", "C9;C10", False, False, False, "https://arxiv.org/abs/2605.30696", "Implicit-field safety-control candidate", "D2/D5 context", "Excluded because it is not Gaussian-map specific and arrived after core set saturation"),
]

# Full-text fields use only statements supported by the cached primary PDFs.
# ``none_found`` means not found in the reviewed full text, not universal absence.
FULLTEXT_FACTS = {
    "2304.00194": {
        "input_representation": "High-dimensional sensor observation plus learned perception map producing a state estimate",
        "map_assumptions": "Calibration and test residuals satisfy the paper's exchangeability assumptions",
        "geometry_authority": "Ground-truth state/trajectory in the evaluated control systems",
        "uncertainty_object": "Conformal prediction region for perception/state-estimation error",
        "query_unit": "Per-sample state estimate and robust safety constraint",
        "output_semantics": "Measurement-robust sampled-data safe control with probabilistic coverage statement",
        "unknown_or_abstention": "No map-level SAFE/OCCUPIED/UNKNOWN label; uncertainty is a conformal set",
        "false_free_direct": "No Gaussian-map false-free label",
        "point_segment_trajectory": "State/control sample and closed-loop trajectory",
        "robot_footprint": "System/task-specific, not a Gaussian footprint certificate",
        "control_model": "Control-affine systems with learned perception",
        "actuator_bounds": "System-specific; not the paper's primary contribution",
        "sampled_data": "Explicit measurement-robust sampled-data CBF construction",
        "terminal_backup": "none_found",
        "theory": "Coverage-to-safety result under stated conformal and system assumptions",
        "exact_assumptions": "Exchangeable calibration/test errors, valid system model, and CBF regularity/robustness conditions",
        "datasets": "F1/10 perception-control case study and paper-specific simulations",
        "learned_or_gt": "Learned perception with ground-truth evaluation",
        "reference_authority": "Ground-truth state used for evaluation, not 3D map geometry",
        "closed_loop": "yes",
        "hardware": "F1/10 platform/case study as reported",
        "runtime": "Paper-specific; not normalized to our 4090",
    },
    "2309.08050": {
        "input_representation": "Analytic sampled-data dynamical system with bounded disturbance and measurement error",
        "map_assumptions": "No learned or Gaussian map",
        "geometry_authority": "Analytic safe set",
        "uncertainty_object": "Bounded disturbance and measurement-error sets",
        "query_unit": "Sampled control update",
        "output_semantics": "Robust high-order CBF inequality for zero-order-hold control",
        "unknown_or_abstention": "none_found",
        "false_free_direct": "Not a map-classification problem",
        "point_segment_trajectory": "Sampled state and intersample evolution",
        "robot_footprint": "System-specific",
        "control_model": "Relative-degree-one or higher nonlinear sampled-data system",
        "actuator_bounds": "Can enter admissible-control set; not Gaussian-specific",
        "sampled_data": "central and explicit",
        "terminal_backup": "none_found",
        "theory": "High-order doubly robust CBF and sampled-data safety conditions",
        "exact_assumptions": "Bounded disturbances/errors, known sampling period, regular dynamics, and feasible robust constraint",
        "datasets": "Analytic/simulation case studies",
        "learned_or_gt": "No learned map",
        "reference_authority": "Analytic model",
        "closed_loop": "simulation",
        "hardware": "none_found",
        "runtime": "No direct 3DGS runtime comparison",
    },
    "2403.02751": {
        "input_representation": "Pretrained anisotropic 3D Gaussian Splatting scene and onboard images for localization",
        "map_assumptions": "Gaussian ellipsoids provide scene geometry adequate for conservative free-space polytopes",
        "geometry_authority": "Paper scene geometry/collision setup; no Protocol V2 hierarchy",
        "uncertainty_object": "Localization robustness; no calibrated map-level uncertainty",
        "query_unit": "Safe polytope corridor and Bézier trajectory",
        "output_semantics": "Collision-free planned trajectory inside certified polytope corridor",
        "unknown_or_abstention": "No explicit map-level UNKNOWN found",
        "false_free_direct": "No one-sided cross-map false-free calibration",
        "point_segment_trajectory": "Trajectory",
        "robot_footprint": "Robot geometry incorporated through obstacle/corridor construction",
        "control_model": "Trajectory planning and vision-based localization",
        "actuator_bounds": "Trajectory feasibility limits; not an actuator-level CBF-QP",
        "sampled_data": "Replanning system, not a sampled-data CBF theorem",
        "terminal_backup": "none_found",
        "theory": "Safe-by-construction corridor/trajectory result under map and localization assumptions",
        "exact_assumptions": "Static accurate map, collision geometry construction, and localization within evaluated regime",
        "datasets": "Synthetic/real Gaussian scenes and 126 hardware flight trials",
        "learned_or_gt": "Learned Gaussian maps",
        "reference_authority": "Experiment collision outcome and scene assets",
        "closed_loop": "yes",
        "hardware": "yes, aerial robot",
        "runtime": "Approximately 2 Hz replanning reported",
    },
    "2405.00362": {
        "input_representation": "Implicit/mesh geometry for robot and environment",
        "map_assumptions": "Valid signed distance and swept-volume representation",
        "geometry_authority": "Exact/sampled geometry used by continuous collision experiments",
        "uncertainty_object": "none_found",
        "query_unit": "Whole swept volume along a trajectory",
        "output_semantics": "Continuous collision-free trajectory objective/constraint",
        "unknown_or_abstention": "none_found",
        "false_free_direct": "No learned-map false-free label",
        "point_segment_trajectory": "Continuous trajectory swept volume",
        "robot_footprint": "Arbitrary robot shape",
        "control_model": "Trajectory generation/optimization",
        "actuator_bounds": "Trajectory limits as configured",
        "sampled_data": "Continuous geometric checking; not sampled-data CBF",
        "terminal_backup": "none_found",
        "theory": "Implicit swept-volume SDF construction and continuous collision objective",
        "exact_assumptions": "Accurate geometry/SDF and optimizer convergence to reported solution",
        "datasets": "Paper geometric planning benchmarks",
        "learned_or_gt": "Geometry representation, not learned 3DGS",
        "reference_authority": "Explicit geometry",
        "closed_loop": "trajectory generation",
        "hardware": "paper-specific demonstrations",
        "runtime": "Reported planner runtime; not normalized to our maps",
    },
    "2405.10142": {
        "input_representation": "Online 3DGS reconstruction from RGB-D active views",
        "map_assumptions": "Current Gaussian reconstruction supports view utility and safety-aware planning",
        "geometry_authority": "Simulator/scene geometry for reconstruction experiments",
        "uncertainty_object": "Reconstruction/view utility rather than calibrated false-free risk",
        "query_unit": "Next-best-view path/trajectory",
        "output_semantics": "Safe active-reconstruction trajectory",
        "unknown_or_abstention": "No explicit one-sided map UNKNOWN label found",
        "false_free_direct": "No cross-map false-free calibration",
        "point_segment_trajectory": "Trajectory",
        "robot_footprint": "Quadrotor safety constraint",
        "control_model": "Active reconstruction planner",
        "actuator_bounds": "Trajectory feasibility as configured",
        "sampled_data": "none_found as theorem",
        "terminal_backup": "none_found",
        "theory": "Optimization formulation; no end-to-end safety theorem transferred here",
        "exact_assumptions": "Sufficient reconstruction quality and valid planner safety representation",
        "datasets": "Simulated supermarket and paper active-reconstruction scenes",
        "learned_or_gt": "Online learned 3DGS",
        "reference_authority": "Simulation ground truth/reconstruction metrics",
        "closed_loop": "active mapping loop",
        "hardware": "simulated quadrotor in reviewed evidence",
        "runtime": "Paper-specific",
    },
    "2409.09868": {
        "input_representation": "Online Gaussian Splatting map built from robot observations",
        "map_assumptions": "Gaussian geometry is usable by the analytic barrier field",
        "geometry_authority": "Paper experiment scenes; no independent cross-map qualification hierarchy",
        "uncertainty_object": "No calibrated one-sided map uncertainty",
        "query_unit": "Current robot state/control against Gaussian barrier",
        "output_semantics": "Minimally invasive CBF-filtered control",
        "unknown_or_abstention": "No explicit map-level UNKNOWN found",
        "false_free_direct": "No one-sided cross-map false-free calibration",
        "point_segment_trajectory": "Point/current-state filtering and closed-loop trajectory",
        "robot_footprint": "Robot radius/extent represented in barrier geometry",
        "control_model": "Reduced-order single/double-integrator-style control used by SAFER-Splat",
        "actuator_bounds": "Paper control constraints; not full quadrotor realization",
        "sampled_data": "Executed discretely; no matching robust sampled-data theorem found",
        "terminal_backup": "none_found",
        "theory": "CBF forward-invariance statement under model/map assumptions",
        "exact_assumptions": "Accurate local Gaussian map, CBF feasibility, model validity, and solver execution",
        "datasets": "Paper synthetic and real navigation scenes",
        "learned_or_gt": "Online learned 3DGS",
        "reference_authority": "Experiment outcomes; no Protocol V2 oracle",
        "closed_loop": "yes",
        "hardware": "yes",
        "runtime": "Real-time/scalable as reported; hardware differs from our audit",
    },
    "2409.16915": {
        "input_representation": "Normalized Gaussian Splat density and robot trajectory",
        "map_assumptions": "Normalized splat supports an upper bound on collision probability",
        "geometry_authority": "Simulator/scene collision geometry and real manipulator experiment",
        "uncertainty_object": "Collision probability bound induced by normalized Gaussian density",
        "query_unit": "Whole trajectory",
        "output_semantics": "Risk-aware optimized trajectory",
        "unknown_or_abstention": "No map-level UNKNOWN found",
        "false_free_direct": "No one-sided cross-map false-free calibration",
        "point_segment_trajectory": "Trajectory",
        "robot_footprint": "Robot geometry represented in collision-risk evaluation",
        "control_model": "Trajectory optimization",
        "actuator_bounds": "Trajectory/robot limits as configured",
        "sampled_data": "Not a sampled-data safety-filter theorem",
        "terminal_backup": "none_found",
        "theory": "Rigorous upper bound on collision probability in the normalized splat",
        "exact_assumptions": "Valid normalized Gaussian representation and optimization/risk-bound assumptions",
        "datasets": "Replica, TUM-RGBD, cluttered simulation, and real manipulator demonstration",
        "learned_or_gt": "Learned normalized Gaussian maps",
        "reference_authority": "Dataset/experiment geometry",
        "closed_loop": "trajectory execution demonstration",
        "hardware": "yes, manipulator",
        "runtime": "Paper reports optimization performance; not a 50 ms filter contract",
    },
    "2505.08510": {
        "input_representation": "Anisotropic Gaussian environment and Gaussian approximation of robot geometry",
        "map_assumptions": "Gaussian overlap is a valid differentiable collision surrogate",
        "geometry_authority": "Synthetic/real experiment collision geometry",
        "uncertainty_object": "Overlap integral, not calibrated epistemic uncertainty",
        "query_unit": "Pose/trajectory overlap objective",
        "output_semantics": "Orientation-aware collision-minimizing trajectory",
        "unknown_or_abstention": "none_found",
        "false_free_direct": "No cross-map one-sided false-free label",
        "point_segment_trajectory": "Trajectory",
        "robot_footprint": "Explicit Gaussian robot model with orientation",
        "control_model": "Differentiable trajectory optimization",
        "actuator_bounds": "Trajectory constraints as configured",
        "sampled_data": "Not a sampled-data CBF theorem",
        "terminal_backup": "none_found",
        "theory": "Closed-form/differentiable field-overlap collision integral",
        "exact_assumptions": "Faithful Gaussian robot/environment approximations and optimizer convergence",
        "datasets": "Synthetic scenes and real robot experiments in the paper",
        "learned_or_gt": "Learned 3DGS environments",
        "reference_authority": "Experiment collision geometry",
        "closed_loop": "trajectory execution/optimization",
        "hardware": "yes",
        "runtime": "Few-second optimization reported even with hundreds of thousands of Gaussians",
    },
    "2509.14421": {
        "input_representation": "Individual anisotropic 3D Gaussian splats converted to inflated ellipsoidal obstacles",
        "map_assumptions": "Each splat's geometry can define a conservative forward collision cone",
        "geometry_authority": "Paper scene/collision setup; no Protocol V2 reference hierarchy",
        "uncertainty_object": "Deterministic splat geometry",
        "query_unit": "Per-splat forward collision cone at a control step",
        "output_semantics": "First-order collision-cone CBF constraint in a QP",
        "unknown_or_abstention": "No explicit map-level UNKNOWN found",
        "false_free_direct": "No one-sided false-free calibration",
        "point_segment_trajectory": "Control step and closed-loop trajectory",
        "robot_footprint": "Minkowski-style obstacle inflation for robot extent",
        "control_model": "Reduced-order safety-critical control with CBF-QP",
        "actuator_bounds": "QP/control bounds as configured",
        "sampled_data": "Discrete implementation; no robust sampled-data theorem found",
        "terminal_backup": "none_found",
        "theory": "Analytic collision-cone geometry yielding a first-order CBF",
        "exact_assumptions": "Valid splat ellipsoid geometry, model/QP assumptions, and cone construction",
        "datasets": "Paper simulation/navigation scenes",
        "learned_or_gt": "Learned 3DGS",
        "reference_authority": "Paper collision environment",
        "closed_loop": "yes",
        "hardware": "none_found in reviewed text",
        "runtime": "Real-time intent; no normalization to our benchmark",
    },
    "2604.18205": {
        "input_representation": "NeRF and Gaussian Splatting reconstructions",
        "map_assumptions": "Rendering representations can be evaluated against independent surface geometry",
        "geometry_authority": "Reference geometry/depth across 19 scenes",
        "uncertainty_object": "Geometry error metrics, not predictive uncertainty",
        "query_unit": "Surface/point geometry metric",
        "output_semantics": "Comparative geometric accuracy score",
        "unknown_or_abstention": "none_found",
        "false_free_direct": "Does not directly define navigation false-free labels",
        "point_segment_trajectory": "Surface/point evaluation",
        "robot_footprint": "none",
        "control_model": "none",
        "actuator_bounds": "not applicable",
        "sampled_data": "not applicable",
        "terminal_backup": "not applicable",
        "theory": "Measurement protocol and comparative evaluation",
        "exact_assumptions": "Reference geometry is aligned and metrics reflect relevant surface fidelity",
        "datasets": "19 scenes reported in the paper",
        "learned_or_gt": "Learned reconstructions with independent reference",
        "reference_authority": "Reference geometry/depth",
        "closed_loop": "no",
        "hardware": "no",
        "runtime": "Evaluation runtime not a control contract",
    },
    "2605.20566": {
        "input_representation": "3DGS field with collision-risk and view-information quantities",
        "map_assumptions": "Gaussian opacity/uncertainty supports AV@R collision risk and expected information gain",
        "geometry_authority": "Simulation scene geometry",
        "uncertainty_object": "AV@R collision risk and information-gain field",
        "query_unit": "Control action in a unified safety/perception QP",
        "output_semantics": "Safe control balancing collision risk and active perception",
        "unknown_or_abstention": "No explicit SAFE/OCCUPIED/UNKNOWN map query found",
        "false_free_direct": "Risk modeled, but no cross-map one-sided false-free calibration",
        "point_segment_trajectory": "Control step and trajectory",
        "robot_footprint": "Paper-specific collision model",
        "control_model": "Nonlinear control-affine dynamics",
        "actuator_bounds": "QP/control set as configured",
        "sampled_data": "Executed discretely; sampled-data robustness not the main theorem",
        "terminal_backup": "none_found",
        "theory": "Safety and perception CBF conditions with AV@R objective",
        "exact_assumptions": "Valid uncertainty/risk field, model, QP feasibility, and scene representation",
        "datasets": "Simulation studies",
        "learned_or_gt": "Learned 3DGS",
        "reference_authority": "Simulation ground truth",
        "closed_loop": "yes, simulation",
        "hardware": "none_found",
        "runtime": "Simulation runtime reported; no target-hardware qualification",
    },
    "2605.30342": {
        "input_representation": "3DGS plus spherical-harmonic anisotropic visibility field",
        "map_assumptions": "Visibility from training views predicts spatially and directionally varying uncertainty",
        "geometry_authority": "Active-mapping benchmark scene references",
        "uncertainty_object": "Anisotropic visibility uncertainty and Bayesian rasterizer output",
        "query_unit": "View/ray uncertainty for next-best-view selection",
        "output_semantics": "Uncertainty estimate and active-mapping action",
        "unknown_or_abstention": "Uncertainty is explicit; no control-level SAFE/OCCUPIED/UNKNOWN label",
        "false_free_direct": "No one-sided navigation false-free calibration",
        "point_segment_trajectory": "View/ray and mapping trajectory",
        "robot_footprint": "not central",
        "control_model": "Active mapping planner",
        "actuator_bounds": "not central",
        "sampled_data": "not a sampled-data CBF method",
        "terminal_backup": "none_found",
        "theory": "Anisotropic visibility representation and Bayesian uncertainty rendering",
        "exact_assumptions": "Training-view visibility is informative of reconstruction uncertainty",
        "datasets": "Paper active-mapping datasets and scenes",
        "learned_or_gt": "Learned 3DGS with uncertainty field",
        "reference_authority": "Benchmark mapping references",
        "closed_loop": "active mapping loop",
        "hardware": "paper-specific; not a safety-control hardware claim",
        "runtime": "Approximately 200 FPS uncertainty rendering reported",
    },
    "2606.00297": {
        "input_representation": "System dynamics, obstacle/barrier functions, and a predicted flow horizon",
        "map_assumptions": "No Gaussian map; barrier model is available",
        "geometry_authority": "Simulation/experiment obstacle model",
        "uncertainty_object": "Prediction/model quantities, not learned-map confidence",
        "query_unit": "Prediction horizon and current QP",
        "output_semantics": "Jointly feasible real-time safe optimal control",
        "unknown_or_abstention": "No map-level UNKNOWN",
        "false_free_direct": "Not a map-classification problem",
        "point_segment_trajectory": "Predicted trajectory/flow",
        "robot_footprint": "Model-specific",
        "control_model": "Nonholonomic/control-affine systems in reported trials",
        "actuator_bounds": "Included in optimal-control constraints",
        "sampled_data": "Real-time repeated optimization",
        "terminal_backup": "Explicit terminal backup safe set",
        "theory": "Predicted-flow CBF and terminal condition supporting recursive feasibility/safety under assumptions",
        "exact_assumptions": "Accurate dynamics/barriers, feasible backup/terminal set, and solver execution",
        "datasets": "100-trial nonholonomic-robot comparisons and paper studies",
        "learned_or_gt": "No learned Gaussian map",
        "reference_authority": "Analytic/simulation obstacles",
        "closed_loop": "yes",
        "hardware": "paper-specific",
        "runtime": "Reported real-time comparison; different workload/hardware",
    },
    "2607.01200": {
        "input_representation": "Anisotropic 3DGS obstacles, full nonlinear quadrotor state, and actuator model",
        "map_assumptions": "Analytic splat collision cones provide adequate obstacle geometry",
        "geometry_authority": "Paper simulation and initial hardware collision setup",
        "uncertainty_object": "Deterministic Gaussian geometry; no cross-map calibrated uncertainty",
        "query_unit": "Full-dynamics control step plus forward-simulated backup policy",
        "output_semantics": "Actuator-aware ECBF/QP action with backup-feasibility bridge",
        "unknown_or_abstention": "No map-level SAFE/OCCUPIED/UNKNOWN label found",
        "false_free_direct": "No one-sided cross-map false-free calibration",
        "point_segment_trajectory": "Control step and backup rollout",
        "robot_footprint": "Quadrotor extent in collision-cone geometry",
        "control_model": "Full nonlinear quadrotor dynamics",
        "actuator_bounds": "Explicit actuator-aware constraints",
        "sampled_data": "Execution-aware design; not identical to our frozen numerical contract",
        "terminal_backup": "Explicit forward-simulated backup CBF/policy",
        "theory": "High-order/exponential collision-cone CBF and backup-feasibility construction",
        "exact_assumptions": "Valid 3DGS geometry, quadrotor/actuator model, backup policy, and QP feasibility",
        "datasets": "Fast-flight simulation plus initial hardware validation",
        "learned_or_gt": "Learned 3DGS",
        "reference_authority": "Experiment collision setup; no Protocol V2 cross-map reference",
        "closed_loop": "yes",
        "hardware": "initial quadrotor hardware validation",
        "runtime": "Paper reports 2.25x faster flight and 47% jerk reduction relative to cited comparison",
    },
    "2607.08948": {
        "input_representation": "Online RGB-D isotropic Gaussian scene reconstruction",
        "map_assumptions": "Isotropic splats support continuous distance/collision probability",
        "geometry_authority": "Simulation and physical manipulator scene observations",
        "uncertainty_object": "Collision probability/distance field, not calibrated epistemic map trust",
        "query_unit": "Manipulator configuration/control step",
        "output_semantics": "Reactive collision-free CBF control",
        "unknown_or_abstention": "No explicit cross-map UNKNOWN gate found",
        "false_free_direct": "No one-sided reference-calibrated false-free contract",
        "point_segment_trajectory": "Reactive control and trajectory",
        "robot_footprint": "Manipulator geometry approximated in collision field",
        "control_model": "6-DoF manipulator reactive control",
        "actuator_bounds": "Controller-specific",
        "sampled_data": "Real-time repeated control; no matching robust sampled-data theorem found",
        "terminal_backup": "none_found",
        "theory": "Continuous Gaussian collision representation embedded in CBF control",
        "exact_assumptions": "Online reconstruction fidelity, isotropic/sphere approximation, valid robot model and feasible controller",
        "datasets": "Simulation and physical robot shared-workspace experiments",
        "learned_or_gt": "Online learned isotropic Gaussian map",
        "reference_authority": "Experiment collision outcomes",
        "closed_loop": "yes",
        "hardware": "yes, physical manipulator",
        "runtime": "Real-time claim in paper; stated scalability/tuning limitations",
    },
}

SEARCH_CLUSTERS = {
    "L1": "3D Gaussian Splatting robot navigation",
    "L2": "Gaussian Splatting collision checking",
    "L3": "Gaussian Splatting trajectory optimization",
    "L4": "Gaussian Splatting CBF safety filter",
    "L5": "Gaussian Splatting reactive control",
    "L6": "Gaussian Splatting uncertainty robotics",
    "L7": "Gaussian Splatting visibility active mapping",
    "L8": "Bayesian 3D Gaussian Splatting uncertainty",
    "L9": "Gaussian Splatting geometry reliability robotics",
    "L10": "Gaussian Splatting free space occupancy",
    "L11": "Gaussian Splatting SLAM uncertainty",
    "L12": "neural implicit map safety certification robot",
    "L13": "selective prediction abstention robotics safety",
    "L14": "conformal risk control robotics safety",
    "L15": "sampled data control barrier function robust",
    "L16": "backup control barrier function terminal safe set",
    "L17": "predictive safety filter terminal set",
    "L18": "continuous collision detection ellipsoids",
    "L19": "swept volume collision checking robot trajectory",
    "L20": "anisotropic Gaussian ellipsoid distance collision",
    "L21": "map quality qualification navigation geometry reference",
    "L22": "risk aware Gaussian control robot",
    "L23": "safe planning learned map uncertainty robotics",
    "L24": "perception aware uncertainty aware control barrier function",
}

MAPS = [
    ("M1", "Replica GT-derived Gaussian map", "GT-derived", "isotropic represented spheres", "3b318a98a454ec5c36410b3c41dfb3dd4a25b7b5a1899f1f2c939fbf24ad0e55", "metric/valid", "Replica mesh", "mesh", "aligned", "yes", "yes", 0, 0, 0, 0, 35, 0, "no learned train/calibration; representative holdout distinct from activated", "no cross-map learned split", "bounded GT-derived mechanism and prevalence claims", "Single synthetic scene; backup stage selected for 35/160 but had zero incremental representative outcome impact; activated-cohort disagreements are selection-biased and reported separately"),
    ("M2", "Replica learned Gaussian candidates", "learned", "mixed", "multiple noncanonical candidates", "partially audited", "Replica mesh", "mesh", "partial", "partial", "partial", None, None, None, None, None, None, "not frozen as two independent maps", "not executable", "NOT_EVALUABLE", "No canonical dual learned-map Protocol V2 cohort"),
    ("M3", "ETH3D Delivery Area learned Gaussian map", "learned", "anisotropic", "frozen Protocol V2 asset", "metric/qualified with caveats", "ETH3D laser/reference bundle", "mesh/depth", "aligned", "yes", "limited", None, None, None, None, None, None, "single scene only", "cannot form two-map split", "bounded map qualification only", "One map; insufficient event-labelled control records"),
    ("M4", "TUM SplaTAM map", "learned RGB-D", "anisotropic", "frozen TUM SplaTAM asset", "metric adapter validated", "TUM RGB-D depth/trajectory", "depth", "partial", "yes", "limited", None, None, None, None, None, None, "no independent cross-map counterpart", "not executable", "static compatibility only", "Reference and representative control-query registry incomplete"),
    ("M5", "TUM Gaussian-SLAM map", "learned RGB-D", "anisotropic", "frozen Gaussian-SLAM asset", "metric adapter validated", "TUM RGB-D depth/trajectory", "depth", "partial", "yes", "limited", None, None, None, None, None, None, "shares source scene with M4", "not independent", "static compatibility only", "Not an independent-scene generalization split"),
    ("M6", "TUM Splatfacto failed route", "learned", "anisotropic", "V1R6 checkpoint lineage", "geometry drift", "TUM RGB-D depth", "depth", "partial", "yes", "yes", None, None, None, None, None, None, "not admissible", "negative control only", "negative geometry claim", "Post-3K drift; forbidden as formal navigation map"),
    ("M7", "Stonehenge SAFER map", "learned/source map", "anisotropic", "official frozen asset", "runtime-compatible", "none", "none", "scenario-local", "yes", "yes", None, None, None, None, None, None, "no authority split", "not evaluable", "runtime/reproduction only", "No independent geometry reference"),
    ("M8", "Flight SAFER map", "learned/source map", "anisotropic", "official frozen asset", "runtime-compatible", "none", "none", "scenario-local", "yes", "yes", None, None, None, None, None, None, "no authority split", "not evaluable", "runtime/reproduction only", "No independent geometry reference"),
    ("M9", "ARKitScenes M1 confidence-aware map", "learned RGB-D", "anisotropic", "frozen ARKit M1 lineage", "metric confidence contract", "ARKit depth/confidence", "depth", "partial", "yes", "limited", None, None, None, None, None, None, "single selected scene; confidence mask contract", "not executable", "map provenance/negative evidence only", "No independent second map and no frozen event-labelled split"),
]

DIRECTION_DETAILS = {
    "D0": ("Convert frozen module, negative-result, and benchmark evidence into one bounded paper strategy.", "Auditable evidence package and contribution plan.", "The contribution is a measurement-backed modular safety assurance and negative-boundary study, not a new controller.", "Gaussian-map robotics and safety-assurance researchers", "SAFER-Splat; Splat-Nav; FastBridge", "Uses the rare activated/representative contrast, deadline failures, and map qualification failures as first-class evidence.", "No new method; rigorous synthesis and bounded benchmark narrative.", "Claim-evidence logic and explicit nonclaims.", "Re-audit frozen records; no new scientific run required.", "Existing Replica GT plus archived cross-dataset negatives.", "Frozen mesh/depth authorities already used.", "None", "high", "Benchmark/measurement or negative-results paper.", "Reviewers may view synthesis as insufficiently novel unless the measurement questions and released artifacts are crisp."),
    "D1": ("Use Core V1 only as a rare-event executable supervisor.", "Typed commit/fail-closed decision for rare states.", "A rare-event positioning of actuator/swept/backup/directional checks improves intervention semantics beyond a current-state CBF.", "Safety-filter and field-robotics community", "FastBridge; Predicted-Flow CBF; SAFER-Splat", "Restricts scope to rare events and typed abstention rather than broad replacement.", "A calibrated rare-event trigger and supervisor.", "Sampled-data terminal/backup obligation.", "Two learned maps with nonzero trigger events and three baselines.", "Two independent learned maps.", "Credible geometry on both maps.", "Optional robot; GPU workstation", "low-medium", "Mechanism note or negative prevalence study.", "FastBridge already couples actuator-aware 3DGS filtering and backup CBF; representative events are zero."),
    "D2": ("Certify continuous robot-footprint segments against anisotropic learned Gaussians quickly.", "Conservative segment status and bound.", "A conservative anisotropic Gaussian swept-footprint certificate with acceleration separates this from point or sampled checks.", "Motion planning and geometric computing", "FOCI; SPLANNING; Implicit Swept Volume SDF", "Targets certified bound and large-scale acceleration rather than trajectory cost alone.", "Bound, acceleration structure, and parity implementation.", "Soundness under explicit Gaussian-to-geometry assumptions.", "Synthetic/learned maps, exact geometry oracle, runtime scale study.", "At least two anisotropic learned maps.", "Meshes or laser scans.", "GPU workstation", "low", "Geometry-method workshop paper.", "Crowded collision literature and unresolved map-to-occupancy authority."),
    "D3": ("Return CERTIFIED_FREE/OCCUPIED/UNKNOWN for control-conditioned point/segment queries with one-sided false-free risk.", "Selective label with risk level and provenance.", "Control-conditioned one-sided false-free calibration across Gaussian maps adds abstention semantics absent from deterministic filters.", "Robot learning, uncertainty, and safety", "GAVIS; conformal perception-based control; Conflict-Aware 3DGS CBF", "Calibrates false-free decisions against independent references across maps, not view uncertainty alone.", "Selective query and calibration protocol.", "Finite-sample one-sided risk statement under explicit exchangeability assumptions.", "Multiple learned maps, disjoint calibration/test, event-rich queries.", "At least two independent learned maps.", "Mesh/depth/laser authority.", "GPU workstation", "low", "Map qualification benchmark or workshop.", "No two-map event-labelled split; conformal assumptions and event scarcity are unresolved."),
    "D4": ("Compute a Gaussian-map-conditioned backup/terminal recoverability set under finite actuation.", "Recoverability label and backup control.", "Coupling anisotropic Gaussian geometry to an actuator-valid terminal safe set yields map-conditioned viability semantics.", "Control and aerial robotics", "FastBridge; Predicted-Flow CBF; SAFER-Splat", "Would require stronger geometry/reference calibration than existing forward backup simulation.", "Backup-set construction and online approximation.", "Recursive feasibility or bounded invariance theorem.", "Dynamic rollouts across at least two learned maps.", "Two independent learned maps.", "Geometry authority plus dynamics truth.", "GPU and optional quadrotor", "low", "Theory/mechanism workshop fallback.", "FastBridge is direct overlap; viability plus learned geometry exceeds eight-week scope."),
    "D5": ("Optimize minimum-intervention executable control continuously rather than enumerate a finite library.", "Actuator-valid control or fail-closed result.", "A certificate-aware continuous optimizer jointly respects segment and terminal checks.", "Optimization and control robotics", "FOCI; SPLANNING; FastBridge", "Optimizes the executable certificate rather than only Gaussian collision cost.", "Differentiable/bilevel solver and fairness study.", "Feasibility and convergence bounds under limited assumptions.", "Strong optimization baselines and closed-loop learned-map trials.", "Two independent learned maps.", "Credible map references.", "GPU workstation", "low", "Optimization workshop fallback.", "FOCI/SPLANNING/FastBridge crowd the space; differentiating all certificate stages is high risk."),
    "D6": ("Budget Gaussian constraints while preserving the frozen safety query result.", "Reduced active set plus equivalence/violation flag.", "Risk-ranked budgeting would reduce computation while preserving a formally stated conservative inclusion.", "Real-time robotics systems", "SAFER-Splat; FastBridge; active-set CBF-QP literature", "Builds on BestD but needs a preservation theorem beyond empirical speed.", "Budgeting rule and equivalence guard.", "Conservative preservation under explicit screening bound.", "Large-map runtime and adversarial missed-constraint tests.", "At least two maps for generalization.", "Reference helpful but not sufficient.", "GPU workstation", "medium-high", "Systems optimization note.", "Existing BestD evidence is efficiency only and overlap risk is high."),
    "D7": ("Measure whether learned Gaussian maps are navigation-qualified under reference-grounded false-free and UNKNOWN metrics.", "Benchmark labels, splits, metrics, and baseline results.", "A cross-map navigation-qualification benchmark centered on one-sided false-free and abstention would fill a measurement gap.", "Mapping, embodied vision, and robotics", "Geometric accuracy evaluation; GAVIS; NavGSim", "Connects map geometry error to navigation-query semantics and reference hierarchy.", "Benchmark protocol, dataset adapters, and metrics.", "Statistical reliability and split rationale, not a control theorem.", "At least two learned maps with references and sufficient events.", "Two or more independent map families/scenes.", "Mesh/depth/laser authority.", "GPU workstation and storage", "medium", "Benchmark/measurement venue.", "Current assets do not yet satisfy two independent learned maps with credible reference and event labels."),
    "D8": ("Gate learned-map use in safety control using confidence; abstain when trust is insufficient.", "USE_MAP or UNKNOWN plus filtered control.", "A calibrated map-trust gate controls when a Gaussian CBF may issue a safety claim.", "Safe robot learning and mapping", "GAVIS; Conflict-Aware 3DGS CBF; conformal perception safety", "Targets control authority and false-free abstention, not only mapping/view selection.", "Confidence gate and end-to-end fail-closed integration.", "Calibration coverage linked to control-query semantics.", "Cross-map learned confidence and closed-loop evaluation.", "At least two learned maps.", "Independent geometry reference.", "GPU workstation", "low", "Safety/uncertainty workshop fallback.", "Map confidence is crowded; no qualified calibration/test split or stable event rate."),
}

POSITIVE_SCORES = {
    "D0": [4, 4, 2, 2, 5, 5, 5, 5, 5, 3, 3, 5, 5, 5],
    "D1": [5, 2, 3, 3, 2, 1, 5, 3, 4, 1, 3, 2, 4, 4],
    "D2": [4, 3, 4, 4, 2, 2, 3, 2, 4, 2, 2, 3, 3, 3],
    "D3": [5, 4, 4, 4, 2, 1, 3, 2, 3, 2, 2, 3, 4, 3],
    "D4": [5, 2, 4, 5, 2, 1, 4, 2, 4, 1, 3, 2, 3, 3],
    "D5": [4, 2, 4, 3, 2, 1, 3, 2, 4, 1, 3, 2, 3, 3],
    "D6": [3, 2, 2, 1, 3, 3, 5, 4, 4, 2, 3, 2, 4, 4],
    "D7": [5, 4, 2, 2, 2, 1, 4, 3, 4, 2, 2, 4, 5, 4],
    "D8": [5, 3, 3, 3, 2, 1, 3, 2, 3, 2, 2, 3, 4, 3],
}

RISK_SCORES = {
    "D0": [2, 1, 1, 1, 1, 1, 1, 2, 1, 1],
    "D1": [4, 5, 3, 5, 3, 3, 3, 5, 4, 3],
    "D2": [4, 4, 3, 4, 4, 4, 4, 4, 4, 3],
    "D3": [4, 3, 4, 5, 4, 4, 3, 4, 5, 3],
    "D4": [5, 5, 3, 5, 5, 5, 4, 5, 4, 3],
    "D5": [5, 5, 3, 5, 4, 5, 4, 5, 4, 3],
    "D6": [5, 5, 3, 3, 2, 2, 3, 4, 3, 4],
    "D7": [3, 3, 4, 5, 2, 3, 2, 4, 5, 2],
    "D8": [4, 4, 4, 5, 3, 4, 3, 4, 5, 3],
}

FATAL_RESULTS = {
    # D0 is assessed by the dedicated Case-D rule rather than new-method gates.
    "D1": [True, True, False, False, False, True, True, False, False, True],
    "D2": [True, True, False, False, False, False, True, True, False, True],
    "D3": [True, True, False, False, False, False, True, True, False, True],
    "D4": [False, True, False, False, False, False, True, True, False, True],
    "D5": [True, True, False, False, False, False, True, True, False, True],
    "D6": [False, True, False, False, True, True, True, False, True, True],
    "D7": [True, True, False, False, False, True, True, True, True, True],
    "D8": [True, True, False, False, False, False, True, False, False, True],
}

EFFORT = {
    # design, literature, method, data, experiments, debug, analysis, writing, best, likely, worst, gpu_h, storage_gb
    "D0": [3, 4, 0, 2, 0, 2, 6, 8, 15, 25, 35, 0, 2],
    "D1": [4, 5, 10, 12, 10, 8, 5, 6, 38, 60, 85, 120, 120],
    "D2": [5, 6, 15, 14, 10, 10, 6, 6, 48, 72, 100, 160, 160],
    "D3": [6, 7, 14, 20, 10, 10, 7, 7, 55, 81, 115, 180, 250],
    "D4": [7, 7, 18, 16, 14, 12, 7, 7, 60, 88, 125, 220, 180],
    "D5": [6, 6, 18, 16, 14, 14, 7, 7, 60, 90, 130, 250, 180],
    "D6": [4, 5, 8, 8, 10, 7, 5, 6, 32, 53, 75, 140, 100],
    "D7": [6, 7, 8, 22, 12, 10, 8, 8, 52, 81, 120, 200, 400],
    "D8": [6, 7, 14, 22, 14, 12, 8, 7, 60, 90, 130, 240, 300],
}

REVIEW_TOP3 = ["D0", "D7", "D6"]
REVIEW_DATA = {
    "D0": {
        "novelty": (6, "Potentially publishable as a measurement/negative-results study; novelty must come from the questions, protocol, and released evidence.", "Reviewed work does not combine activated-versus-representative behavior, deadline failures, and map-qualification failures as first-class evidence.", "One GT-derived scene and mainly negative cross-dataset evidence make a narrative synthesis insufficient.", "Without new measurement questions and reusable artifacts, this is an internal audit.", "Formal evaluation questions, claim-evidence table, protocol/artifact release, and explicit comparison with prior evaluation scopes.", "BORDERLINE"),
        "theory": (6, "Defensible only as a measurement/negative-boundary study, not a controller or certification contribution.", "Respects frozen claim boundaries and can formalize open safety obligations.", "Modular safety assurance may still imply system-level safety; control-theory novelty is minimal.", "Fatal if the package is only retrospective synthesis or uses certified-safe language.", "Denominators and intervals, claim/nonclaim table, formal obligation taxonomy, deadline tails, and artifact release.", "WEAK_ACCEPT"),
        "systems": (8, "Best near-term systems direction if framed as bounded measurement and assurance.", "Eight-week fit, no new runs, and an unusually useful stress-versus-representative contrast.", "Only one synthetic GT-derived map; no learned-map, hardware, or real-time qualification.", "Fatal if the audit artifacts and questions are not independently useful.", "Re-audit frozen records, preserve cohort separation, analyze 116/260 deadline misses, and trace every claim.", "ACCEPT"),
        "data": (7, "Best-supported under the frozen evidence if strictly bounded to measurement, assurance, and negative results.", "A-tier aligned mesh, preregistered representative holdout, and no post-result resampling.", "The only rate-evaluable map is synthetic and GT-derived; all informative error events are zero.", "Any learned-map or general-navigation positioning would collapse the quantitative contribution.", "Authority table, exact zero-event intervals, GT-derived versus learned-map separation, and explicit baseline limitations.", "WEAK_ACCEPT"),
    },
    "D7": {
        "novelty": (8, "The strongest novelty gap: reference-grounded one-sided false-free and UNKNOWN qualification links map error to navigation-query semantics.", "Distinct from geometric accuracy, navigation, and active-mapping uncertainty when treated as a qualification target.", "The repository cannot currently instantiate the proposed benchmark.", "The benchmark claim is non-executable without two independent reference-qualified learned-map cohorts.", "Two learned-map families/scenes, authority/alignment, frozen labels, confidence intervals, and direct baselines.", "WEAK_ACCEPT"),
        "theory": (4, "A credible gap exists, but navigation-qualified needs bounded statistical semantics and is not executable now.", "Reference hierarchy and one-sided errors separate map truth from control guarantees.", "Zero/missing positive events prevent statistical reliability; M4/M5 are not independent.", "No admissible two-map learned cohort with sufficient labelled events exists.", "Two independent learned maps, preregistered queries, held-out splits, power/intervals, and a non-safety nonclaim.", "REJECT"),
        "systems": (3, "Worthwhile concept, but the frozen evidence does not provide its minimum executable cohort.", "Important learned-map question with strong adapters and reference hierarchy.", "No two independent maps, no event records on eligible maps, no closed-loop or hardware evidence, and 81 likely days.", "Cannot create a cross-map split or baseline table within the frozen eight-week scope.", "Canonical learned maps, aligned references, frozen event registries, reliability intervals, and identical baseline inputs.", "STRONG_REJECT"),
        "data": (2, "Valuable benchmark concept whose frozen assets cannot instantiate it.", "Leakage controls and reference hierarchy are well conceived.", "No learned map has an executable representative query/reference contract; M1 is GT-derived and M4/M5 share a scene.", "The required two-map reference-complete learned cohort is absent.", "Independent maps, authoritative aligned references, representative queries, map-level splits, informative events, and normalized baselines.", "STRONG_REJECT"),
    },
    "D6": {
        "novelty": (4, "Without a Gaussian-specific preservation result, this resembles generic active-set screening applied to a crowded setting.", "A conservative-inclusion theorem could create a real difference.", "BestD shows efficiency only; risk-ranked selection is not itself novel.", "Without a nontrivial Gaussian/query preservation theorem, the contribution is application engineering.", "Invariant/equivalence proof, generic active-set comparison, adversarial misses, and two-map scaling.", "REJECT"),
        "theory": (5, "Potentially theorem-bearing only if heuristic ranking becomes a rigorous screening result.", "Targets a real bottleneck and identifies the need for an equivalence guard.", "The full query may itself be unqualified; map uncertainty, sampled execution, actuators, tolerances, and deadlines remain open.", "Without a computable omitted-constraint bound, it remains empirical pruning.", "Screening theorem, tolerance treatment, adversarial tests, deadline tails, and two-map evaluation.", "BORDERLINE"),
        "systems": (4, "Plausible runtime project, but current evidence shows pruning efficiency rather than preserved safety or representative utility.", "BestD and profiling are reusable and directly target deadline misses.", "Representative activation is 0/160; no target hardware or authoritative multi-map evidence; likely effort is 53 days.", "Without a screening bound and adversarial tests, the decisive constraint may be removed.", "Preservation certificate, boundary suite, two maps, p95/p99 timing, and representative target-hardware trials.", "REJECT"),
        "data": (3, "Neither preservation validity nor generalization is supported by the frozen evaluation evidence.", "The card correctly treats speed alone as insufficient.", "No cross-map split; M1 has zero risk events; M7/M8 lack independent geometry authority.", "Current data cannot reveal safety-critical pruning failures, and no conservative guard exists.", "Equivalence result, adversarial event-positive suite, two maps, full-versus-budgeted measurements, and matched baselines.", "REJECT"),
    },
}

FINAL_STATUS = "EXISTING_EVIDENCE_CONSOLIDATION_IS_HIGHEST_EXPECTED_VALUE"
FINAL_DECISION = "FREEZE_MODULAR_SAFETY_ASSURANCE_OR_NEGATIVE_BENCHMARK_PAPER_STRATEGY"
ONLY_NEXT_TASK = "WRITE_FROZEN_PAPER_CONTRIBUTION_AND_EXPERIMENT_PLAN_V1"
